/*
  SEO helpers. A single typed buildMetadata factory produces Next Metadata for
  every page: title, description, an absolute canonical with a trailing slash,
  Open Graph, and a Twitter summary_large_image card. The homepage default,
  title template, and metadataBase live in app/layout.tsx.

  The default Open Graph image is provided by the file based convention in
  app/opengraph-image.tsx, so it is not set here; Next merges it into every
  route automatically.
*/
import type { Metadata } from "next";
import { siteConfig } from "@/lib/site";

/* The canonical origin, with any trailing slash stripped, for example
   "https://austinsleephealth.com". Paths are appended to this. */
export const siteUrl = siteConfig.domain.replace(/\/+$/, "");

/*
  The default social share image is generated by app/opengraph-image.tsx and is
  served at this route. A page that declares its own openGraph does not inherit
  the root file based image, so buildMetadata references it explicitly on every
  page. metadataBase resolves this relative path to an absolute URL.
*/
const OG_IMAGE_PATH = "/opengraph-image";
const OG_IMAGE_ALT =
  "Austin Sleep & Airway Health, airway and sleep care in Austin, TX";

/*
  Build an absolute page URL from a path, always with a trailing slash to match
  the trailingSlash: true config. The root path "/" resolves to the origin plus
  a single slash.
*/
export function absoluteUrl(path: string): string {
  if (path.startsWith("http://") || path.startsWith("https://")) return path;
  const leading = path.startsWith("/") ? path : `/${path}`;
  const withTrailing = leading.endsWith("/") ? leading : `${leading}/`;
  return `${siteUrl}${withTrailing}`;
}

/*
  Build an absolute URL for a static asset, for example a logo or an image.
  Assets never take a trailing slash.
*/
export function siteAsset(path: string): string {
  const leading = path.startsWith("/") ? path : `/${path}`;
  return `${siteUrl}${leading}`;
}

export interface BuildMetadataParams {
  /** Page title. Used as the template segment unless titleAbsolute is true. */
  title: string;
  /** Meta description. */
  description: string;
  /** Absolute path with a trailing slash, for example "/about-us/". */
  path: string;
  /*
    When true the title is used verbatim and ignores the parent title template.
    Service pages use this because their frontmatter titles already carry the
    practice branding.
  */
  titleAbsolute?: boolean;
  /** Open Graph type. Defaults to "website". */
  ogType?: "website" | "article";
  /** ISO published time, only used when ogType is "article". */
  publishedTime?: string;
  /** When true, the page is marked noindex, nofollow. */
  noIndex?: boolean;
}

/*
  Produce a typed Metadata object. The document title flows through the parent
  template (defined in app/layout.tsx) unless titleAbsolute is set. The Open
  Graph and Twitter titles always carry the full branded form so shared links
  read well regardless of the template.
*/
export function buildMetadata(params: BuildMetadataParams): Metadata {
  const {
    title,
    description,
    path,
    titleAbsolute = false,
    ogType = "website",
    publishedTime,
    noIndex = false,
  } = params;

  const canonical = absoluteUrl(path);
  const brandedTitle = titleAbsolute
    ? title
    : `${title} | ${siteConfig.name}`;

  const images = [
    { url: OG_IMAGE_PATH, width: 1200, height: 630, alt: OG_IMAGE_ALT },
  ];

  const openGraph: Metadata["openGraph"] =
    ogType === "article"
      ? {
          title: brandedTitle,
          description,
          url: canonical,
          siteName: siteConfig.name,
          locale: "en_US",
          type: "article",
          publishedTime,
          authors: [siteConfig.name],
          images,
        }
      : {
          title: brandedTitle,
          description,
          url: canonical,
          siteName: siteConfig.name,
          locale: "en_US",
          type: "website",
          images,
        };

  return {
    title: titleAbsolute ? { absolute: title } : title,
    description,
    alternates: { canonical },
    openGraph,
    twitter: {
      card: "summary_large_image",
      title: brandedTitle,
      description,
      images: [OG_IMAGE_PATH],
    },
    ...(noIndex ? { robots: { index: false, follow: false } } : {}),
  };
}
